### ISSUE TITLE
 'class' as text multiple times  in csv file

### ISSUE THREAD

**Issue by poojab** [DrNeuroSurg/OCRwithVisionAndCoreML-Part4#1]
Finally :) thanks @DrNeuroSurg 

used it.. but it has issue while creating csv file it adds 'class' as text multiple times.

**Comment by DrNeuroSurg** [comment]
This is "by design" - if you start to generate a new training-set the *.csv file will NOT be overwritten ... 
This means you have every time start in a fresh (and empty) destination directory.
OR modify the code so to not overwrite the csv-file (take a look into CSVExport) and also provide a new starting counter for the filenames (an make sure, your characters to train are not modified)
